In [14]:
import numpy as np

string1 = "hi my name Python"
string2 = "python is very fast"

print(np.char.add(string1, string2))
print()

print(np.char.multiply([string1, string2], [2, 5]))
print()

print(np.char.center(string1, 50, "*"))
print()

print(np.char.capitalize([string1, string2]))
print()

print(np.char.title([string1, string2]))
print()

print(np.char.upper([string1, string2]))
print()

print(np.char.lower([string1, string2]))
print()

print(np.char.upper([string1, string2]))
print()

print(np.char.replace([string1, string2], ['hi', 'is'], ['hello', 'was']))
print()

print(np.char.join('---', [string1, string2]))
print()

hi my name Pythonpython is very fast

['hi my name Pythonhi my name Python'
 'python is very fastpython is very fastpython is very fastpython is very fastpython is very fast']

****************hi my name Python*****************

['Hi my name python' 'Python is very fast']

['Hi My Name Python' 'Python Is Very Fast']

['HI MY NAME PYTHON' 'PYTHON IS VERY FAST']

['hi my name python' 'python is very fast']

['HI MY NAME PYTHON' 'PYTHON IS VERY FAST']

['hello my name Python' 'python was very fast']

['h---i--- ---m---y--- ---n---a---m---e--- ---P---y---t---h---o---n'
 'p---y---t---h---o---n--- ---i---s--- ---v---e---r---y--- ---f---a---s---t']



In [29]:
arr1 = np.random.randint(100, size=(4,4))
arr2 = np.random.randint(100, size=(4,4))

arr3 = np.multiply(arr1, arr2)
print('arr2*arr1:\n' ,arr3, '\n')

arr4 = np.divide(arr3, arr1)
print('(arr2*arr1)/arr1:\n', arr4, '\n')

arr5 = np.add(arr1, arr4)
print('arr1+((arr2*arr1)/arr1):\n', arr5, '\n')

arr6 = np.subtract(arr5, arr1)
print('arr1+((arr2*arr1)/arr1)-arr1:\n', arr6, '\n')

arr2*arr1:
 [[3654 5712  159 5846]
 [2496  351  348  891]
 [ 168  228  693   13]
 [ 378  195  574   74]] 

(arr2*arr1)/arr1:
 [[58. 84.  3. 74.]
 [52.  9. 58. 27.]
 [ 7. 19. 99.  1.]
 [42.  3. 82.  2.]] 

arr1+((arr2*arr1)/arr1):
 [[121. 152.  56. 153.]
 [100.  48.  64.  60.]
 [ 31.  31. 106.  14.]
 [ 51.  68.  89.  39.]] 

arr1+((arr2*arr1)/arr1)-arr1:
 [[58. 84.  3. 74.]
 [52.  9. 58. 27.]
 [ 7. 19. 99.  1.]
 [42.  3. 82.  2.]] 



In [79]:
array = np.random.randint(20, size=(6,6))

print('array:\n', array, '\n')

print('Sorted array:')
print(np.sort(array))
print()

print('Sorted array by rows:')
print(np.sort(array, axis=0))
print()

print('Sorted array by columns:')
print(np.sort(array, axis=1))
print()

print("Row's and Column's index where 8 is found:")
print(np.array(np.where(array == 8)))
print()

print("Min and Max:", end = " ")
print(np.min(array), end = " ")
print(np.max(array))
print()

print("Min and Max by columns:", end = " ")
print(np.min(array, axis=0), end = " ")
print(np.max(array, axis=0))
print("Index of min and max by columns:", end = " ")
print(np.argmin(array, axis=0), end = " ")
print(np.argmax(array, axis=0))
print()

print("All elements are zero:", end = " ")
print(np.all(array == 0))
print()

print("Any elements are zero:", end = " ")
print(np.any(array == 0))
print()

array:
 [[ 4 18  3 13  4 13]
 [ 3 18 19  3 14 10]
 [ 0 19  6  0  7  8]
 [18  2 12  1 15  9]
 [ 1  7  8  5  9  3]
 [ 4 15  6  4  1  2]] 

Sorted array:
[[ 3  4  4 13 13 18]
 [ 3  3 10 14 18 19]
 [ 0  0  6  7  8 19]
 [ 1  2  9 12 15 18]
 [ 1  3  5  7  8  9]
 [ 1  2  4  4  6 15]]

Sorted array by rows:
[[ 0  2  3  0  1  2]
 [ 1  7  6  1  4  3]
 [ 3 15  6  3  7  8]
 [ 4 18  8  4  9  9]
 [ 4 18 12  5 14 10]
 [18 19 19 13 15 13]]

Sorted array by columns:
[[ 3  4  4 13 13 18]
 [ 3  3 10 14 18 19]
 [ 0  0  6  7  8 19]
 [ 1  2  9 12 15 18]
 [ 1  3  5  7  8  9]
 [ 1  2  4  4  6 15]]

Row's and Column's index where 8 is found:
[[2 4]
 [5 2]]

Min and Max: 0 19

Min and Max by columns: [0 2 3 0 1 2] [18 19 19 13 15 13]
Index of min and max by columns: [2 3 0 2 5 5] [3 2 1 0 3 0]

All elements are zero: False

Any elements are zero: True



In [76]:
large_array = np.random.randint(100, size=(4032000))
print("Large array:")
print(large_array.reshape(1920, 2100))
print()

sub_arrs = int(1920*2100/120/100)
print(f"Splitting the array into {sub_arrs} sub-arrays:")
splitted_array = np.split(large_array, sub_arrs)
for a in splitted_array:
    print(np.array(a).reshape(120, 100))
    print()

Large array:
[[80  5 76 ... 28 37 92]
 [30 10 79 ... 30 93 88]
 [29 60  5 ... 66 70 45]
 ...
 [84 69 65 ... 15 66 62]
 [12 88 16 ...  2 20 80]
 [89 74 11 ... 20 40 39]]

Splitting the array into 336 sub-arrays:
[[80  5 76 ... 25 93 83]
 [52 87 33 ... 90 93 35]
 [31 66  6 ... 22 16  3]
 ...
 [42 75 63 ... 33 33 46]
 [23  0 52 ... 14  4 51]
 [98 85 11 ... 18 48 20]]

[[71 37 58 ... 82 76 95]
 [11  5 42 ... 61 97 24]
 [52 18 67 ... 31 67 62]
 ...
 [75 94 99 ... 50 45 91]
 [22 99 94 ... 63 85 99]
 [ 0 72 12 ... 42 52  5]]

[[13 23 33 ... 93 63 48]
 [53 74 17 ... 13 37 49]
 [28 92 16 ... 74 14 74]
 ...
 [71 32 13 ... 88 32 60]
 [33 91 99 ...  3 70 47]
 [ 1 99 68 ... 77 93  0]]

[[78 39 14 ... 78 88 32]
 [12 69 49 ... 97 82 80]
 [91 23 70 ...  2 66 26]
 ...
 [74 81  9 ... 36  8 57]
 [ 9 80 24 ... 50 13  7]
 [28  2 41 ... 74 59 59]]

[[73 70 60 ... 41 83 88]
 [84 93 51 ... 40  2 38]
 [70 11 48 ... 99 95 62]
 ...
 [13  1  8 ... 77 14 26]
 [28 94 38 ... 34 91  1]
 [19 88 90 ... 37 41 24]]

[[85

In [73]:
int_array = np.random.randint(20, size=(4,2))
print("Integer array:")
print(int_array)
print()

print("class: ", type(int_array))
print("datatype: ", int_array.dtype)
print("shape: ", int_array.shape)
print("size: ", int_array.size)
print("no. of bytes: ", int_array.nbytes)
print("dimension: ", int_array.ndim)
print()

int_array:
[[12  4]
 [19  6]
 [16  6]
 [ 4 14]]

class:  <class 'numpy.ndarray'>
datatype:  int64
shape:  (4, 2)
size:  8
no. of bytes:  64
dimension:  2



In [75]:
stat_array = np.random.randint(30, size=(4,4))
print("Array:")
print(stat_array)
print()

print("Row-wise Mean:", end = " ")
print(np.mean(stat_array, axis=1))
print("Column-wise Mean:", end = " ")
print(np.mean(stat_array, axis=0))
print()

print("Row-wise Median:", end = " ")
print(np.median(stat_array, axis=1))
print("Column-wise Median:", end = " ")
print(np.median(stat_array, axis=0))
print()

print("Row-wise Variance:", end = " ")
print(np.var(stat_array, axis=1))
print("Column-wise Variance:", end = " ")
print(np.var(stat_array, axis=0))
print()

Array:
[[ 2 28 18 15]
 [21  2  1  9]
 [26 16  2 23]
 [17 22 24  7]]

Row-wise Mean: [15.75  8.25 16.75 17.5 ]
Column-wise Mean: [16.5  17.   11.25 13.5 ]

Row-wise Median: [16.5  5.5 19.5 19.5]
Column-wise Median: [19. 19. 10. 12.]

Row-wise Variance: [86.1875 63.6875 85.6875 43.25  ]
Column-wise Variance: [80.25   93.     99.6875 38.75  ]

