In [1]:
import numpy as np
import numpy.matlib as matlib
import numpy.linalg as la

# Question 1
Consider a matrix A of size nxn(n>=2) and a sub matrix B of size mxm (m<=n).
1. Find the number of submatrix
2. Max, min, average of each submatrix
3. Determinant of each submatrix
4. Inverse of each submatrix

**Assumption: "n" should be even and "m" should be divisible by "n".**

**The element of one submatrix is not matching with other element of submatrix.**

In [3]:
n = int(input("Enter the value of n: "))
# arr = np.mat(input("Enter the matrix as string: "))
arr = np.arange(1, n*n+1).reshape(n, n)
arr = np.array(arr)

m = int(input("Enter the value of m: "))
print(arr)

subarr = []
for i in range(0,n,m):
    temp = []
    for j in range(0,n,m):
        temp.append(arr[i:i+m, j:j+m])
    subarr.append(temp)

subarr = np.array(subarr)
print(subarr)


num_sub = len(subarr)*len(subarr[0])
print("Number of submatrix:", num_sub)


maxarr = []
for a in subarr:
    temp = []
    for b in a:
        temp.append(np.max(b))
    maxarr.append(temp)

maxarr = np.array(maxarr)
print()
print("The max value: ")
print(maxarr)


minarr = []
for a in subarr:
    temp = []
    for b in a:
        temp.append(np.min(b))
    minarr.append(temp)

minarr = np.array(minarr)
print()
print("The min value: ")
print(minarr)


avgarr = []
for a in subarr:
    temp = []
    for b in a:
        temp.append(np.average(b))
    avgarr.append(temp)

avgarr = np.array(avgarr)
print()
print("The average value: ")
print(avgarr)


detarr = []
for a in subarr:
    temp = []
    for b in a:
        temp.append(la.det(b))
    detarr.append(temp)

detarr = np.array(detarr)
print()
print("The determinant value: ")
print(detarr)


invarr = []
for a in subarr:
    temp = []
    for b in a:
        try:
            temp.append(la.inv(b))
        except la.LinAlgError:
            temp.append(np.zeros((m,m)))
    invarr.append(temp)

invarr = np.array(invarr)
print()
print("Null Matrices are for non-invertible")
print("The inverse matrices: ")
print(invarr)

Enter the value of n: 6
Enter the value of m: 3
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[[[ 1  2  3]
   [ 7  8  9]
   [13 14 15]]

  [[ 4  5  6]
   [10 11 12]
   [16 17 18]]]


 [[[19 20 21]
   [25 26 27]
   [31 32 33]]

  [[22 23 24]
   [28 29 30]
   [34 35 36]]]]
Number of submatrix: 4

The max value: 
[[15 18]
 [33 36]]

The min value: 
[[ 1  4]
 [19 22]]

The average value: 
[[ 8. 11.]
 [26. 29.]]

The determinant value: 
[[ 2.13162821e-14  0.00000000e+00]
 [ 0.00000000e+00 -4.26325641e-14]]

Null Matrices are for non-invertible
The inverse matrices: 
[[[[-2.81474977e+14  5.62949953e+14 -2.81474977e+14]
   [ 5.62949953e+14 -1.12589991e+15  5.62949953e+14]
   [-2.81474977e+14  5.62949953e+14 -2.81474977e+14]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00]]]


 [[[ 0.00000000e+00  0.000

# Question 2
Consider a matrix A of size nxn(n>=2) and a sub matrix B of size mxm (m<=n).
1. Find the number of submatrix
2. Max, min, average of each submatrix
3. Determinant of each submatrix
4. Inverse of each submatrix

In [5]:
n = int(input("Enter the value of n: "))
# arr = np.mat(input("Enter the matrix as string: "))
arr = np.arange(1, n*n+1).reshape(n, n)
arr = np.array(arr)

m = int(input("Enter the value of m: "))
print(arr)

subarr = []
for i in range(n-m+1):
    temp = []
    for j in range(n-m+1):
        temp.append(arr[i:i+m, j:j+m])
    subarr.append(temp)

subarr = np.array(subarr)
print(subarr)


num_sub = len(subarr)*len(subarr[0])
print("Number of submatrix:", num_sub)


maxarr = []
for a in subarr:
    temp = []
    for b in a:
        temp.append(np.max(b))
    maxarr.append(temp)

maxarr = np.array(maxarr)
print()
print("The max value: ")
print(maxarr)


minarr = []
for a in subarr:
    temp = []
    for b in a:
        temp.append(np.min(b))
    minarr.append(temp)

minarr = np.array(minarr)
print()
print("The min value: ")
print(minarr)


avgarr = []
for a in subarr:
    temp = []
    for b in a:
        temp.append(np.average(b))
    avgarr.append(temp)

avgarr = np.array(avgarr)
print()
print("The average value: ")
print(avgarr)


detarr = []
for a in subarr:
    temp = []
    for b in a:
        temp.append(la.det(b))
    detarr.append(temp)

detarr = np.array(detarr)
print()
print("The determinant value: ")
print(detarr)


invarr = []
for a in subarr:
    temp = []
    for b in a:
        try:
            temp.append(la.inv(b))
        except la.LinAlgError:
            temp.append(np.zeros((m,m)))
    invarr.append(temp)

invarr = np.array(invarr)
print()
print("Null Matrices are for non-invertible")
print("The inverse matrices: ")
print(invarr)

Enter the value of n: 5
Enter the value of m: 2
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[[[ 1  2]
   [ 6  7]]

  [[ 2  3]
   [ 7  8]]

  [[ 3  4]
   [ 8  9]]

  [[ 4  5]
   [ 9 10]]]


 [[[ 6  7]
   [11 12]]

  [[ 7  8]
   [12 13]]

  [[ 8  9]
   [13 14]]

  [[ 9 10]
   [14 15]]]


 [[[11 12]
   [16 17]]

  [[12 13]
   [17 18]]

  [[13 14]
   [18 19]]

  [[14 15]
   [19 20]]]


 [[[16 17]
   [21 22]]

  [[17 18]
   [22 23]]

  [[18 19]
   [23 24]]

  [[19 20]
   [24 25]]]]
Number of submatrix: 16

The max value: 
[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]

The min value: 
[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]

The average value: 
[[ 4.  5.  6.  7.]
 [ 9. 10. 11. 12.]
 [14. 15. 16. 17.]
 [19. 20. 21. 22.]]

The determinant value: 
[[-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]
 [-5. -5. -5. -5.]]

Null Matrices are for non-invertible
The inverse matrices: 
[[[[-1.4  0.4]
   [ 1.2 -0.2]